=== tjwoodall/individuals-other-income-api/resources/public/api/conf/3.0/schemas/other_retrieve/def2/other_retrieve_response.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "TY 2023-24 to TY 2025-26",
  "type": "object",
  "properties": {
    "submittedOn": {"$ref": "../../other_definitions.json#/definitions/submittedOn"},
    "postCessationReceipts": {"$ref": "../../other_definitions.json#/definitions/postCessationReceipts"},
    "businessReceipts": {"$ref": "../../other_definitions.json#/definitions/businessReceipts"},
    "allOtherIncomeReceivedWhilstAbroad": {"$ref": "../../other_definitions.json#/definitions/allOtherIncomeReceivedWhilstAbroad"},
    "overseasIncomeAndGains": {"$ref": "../../other_definitions.json#/definitions/overseasIncomeAndGains"},
    "chargeableForeignBenefitsAndGifts": {"$ref": "../../other_definitions.json#/definitions/chargeableForeignBenefitsAndGifts"},
    "omittedForeignIncome": {"$ref": "../../other_definitions.json#/definitions/omittedForeignIncome"}
  },
  "required": ["submittedOn"]
}

=== tjwoodall/individuals-other-income-api/resources/public/api/conf/3.0/examples/otherIncome/other_retrieve/def2/retrieve_response.json
{
  "submittedOn": "2025-12-07T14:44:58.128Z",
  "postCessationReceipts": [
    {
      "customerReference": "String",
      "businessName": "Business Name",
      "dateBusinessCeased": "2025-05-30",
      "businessDescription": "Description",
      "incomeSource": "string",
      "amount": 1999.99,
      "taxYearIncomeToBeTaxed": "2025-26"
    }
  ],
  "businessReceipts": [
    {
      "grossAmount": 1999.99,
      "taxYear": "2025-26"
    }
  ],
  "allOtherIncomeReceivedWhilstAbroad": [
    {
      "countryCode": "FRA",
      "amountBeforeTax": 1999.99,
      "taxTakenOff": 1999.99,
      "specialWithholdingTax": 1999.99,
      "foreignTaxCreditRelief": true,
      "taxableAmount": 1999.99,
      "residentialFinancialCostAmount": 1999.99,
      "broughtFwdResidentialFinancialCostAmount": 1999.99
    }
  ],
  "overseasIncomeAndGains": {
    "gainAmount": 1999.99
  },
  "chargeableForeignBenefitsAndGifts": {
    "transactionBenefit": 1999.99,
    "protectedForeignIncomeSourceBenefit": 1999.99,
    "protectedForeignIncomeOnwardGift": 1999.99,
    "benefitReceivedAsASettler": 1999.99,
    "onwardGiftReceivedAsASettler": 1999.99
  },
  "omittedForeignIncome": {
    "amount": 1999.99
  }
}
